version: '3.8'

services:
  flask-app:
    build: .
    ports:
      - 5000:5000

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus-containerized-app.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - flask-app
  
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
    depends_on:
      - prometheus
