global:
  scrape_interval: 15s

  external_labels:
    monitor: 'codelab-monitor'

# Scraping prometheus itself for a first look into the tool
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
